<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AutoMapper\Budget\**" />
    <Compile Remove="AutoMapper\Logs\**" />
    <Compile Remove="Interfaces\IBudget\**" />
    <Compile Remove="Interfaces\ILogs\**" />
    <EmbeddedResource Remove="AutoMapper\Budget\**" />
    <EmbeddedResource Remove="AutoMapper\Logs\**" />
    <EmbeddedResource Remove="Interfaces\IBudget\**" />
    <EmbeddedResource Remove="Interfaces\ILogs\**" />
    <None Remove="AutoMapper\Budget\**" />
    <None Remove="AutoMapper\Logs\**" />
    <None Remove="Interfaces\IBudget\**" />
    <None Remove="Interfaces\ILogs\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AutoMapper\Payment\" />
    <Folder Include="DTO\Budget\" />
    <Folder Include="DTO\Logs\" />
    <Folder Include="Interfaces\IMasterTable\" />
    <Folder Include="DTO\Opex\" />
    <Folder Include="DTO\Payment\RevenueEntry\Responses\" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.74.0.4162" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.28" />
    <PackageReference Include="NPOI" Version="2.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fincore.Domain\Fincore.Domain.csproj" />
  </ItemGroup>

</Project>
