<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\Capex\" />
    <Folder Include="Services\MasterTable\" />
    <Folder Include="Services\Budget\" />
    <Folder Include="Services\Logs\" />
    <Folder Include="Services\Payment\" />
    <Folder Include="Services\Opex\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.28" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fincore.Application\Fincore.Application.csproj" />
    <ProjectReference Include="..\Fincore.Domain\Fincore.Domain.csproj" />
  </ItemGroup>

</Project>
