# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fincore-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      # 1. Publish application
      - name: Publish application
        run: dotnet publish -c Release --no-build --self-contained false -o ./publish

      # 2. ADD THIS STEP HERE 👇
      - name: Check publish size and largest files
        shell: pwsh
        run: |
          $files = Get-ChildItem ./publish -Recurse -File

          $size = ($files | Measure-Object -Property Length -Sum).Sum

          Write-Host "TOTAL PUBLISH SIZE: $([math]::Round($size / 1MB, 2)) MB"

          Write-Host "========== TOP 30 LARGEST FILES =========="

          $files |
            Sort-Object Length -Descending |
            Select-Object -First 30 FullName,
              @{Name="SizeMB";Expression={[math]::Round($_.Length / 1MB, 2)}} |
            Format-Table -AutoSize

      # 3. Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish


  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

      - name: Verify publish folder
        shell: pwsh
        run: |
          Get-ChildItem "${{ github.workspace }}/publish"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_945F908E97AF4013BC4E6617B5CB0CC7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7A146135AF524DE7AED4BBBAD0CE2B7B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_38B8B308D7D5403DB39054F82625DA6E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fincore-app'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish
